# Support for AppVeyor CI -- https://www.appveyor.com/
# Copyright (C) Markus Franz Xaver Johannes Oberhumer

os: Visual Studio 2015

environment:
  matrix:
    - { C: msvc-10.0-x86, CL_VERSION: 16.00, VS_VERSION: 2010 }
### - { C: msvc-10.0-x64, CL_VERSION: 16.00, VS_VERSION: 2010 } # AppVeyor: x64 compiler is not installed
    - { C: msvc-11.0-x86, CL_VERSION: 17.00, VS_VERSION: 2012 }
### - { C: msvc-11.0-x64, CL_VERSION: 17.00, VS_VERSION: 2012 } # AppVeyor: x64 compiler is not installed
    - { C: msvc-12.0-x86, CL_VERSION: 18.00, VS_VERSION: 2013 }
    - { C: msvc-12.0-x64, CL_VERSION: 18.00, VS_VERSION: 2013 }
    - { C: msvc-14.0-x86, CL_VERSION: 19.00, VS_VERSION: 2015 }
    - { C: msvc-14.0-x64, CL_VERSION: 19.00, VS_VERSION: 2015 }

init:
  - git config --global core.autocrlf input

install:
  - cd c:\projects
  - mkdir build build\%C% deps
  - cd c:\projects\upx
  - git submodule update --init --recursive
  - cd c:\projects\deps
  - appveyor DownloadFile "https://download.freenas.org/distfiles/ucl-1.03.tar.gz"
  - appveyor DownloadFile "http://prdownloads.sourceforge.net/libpng/zlib-1.2.8.tar.gz?download"
  - tar -xzf ucl-1.03.tar.gz
  - sed -i '/snprintf  *_v*snprintf/d' ucl-1.03/acc/acc_auto.h
  - tar -xzf zlib-1.2.8.tar.gz
  - git clone https://github.com/upx/upx-testsuite
  - if "%C%"=="msvc-10.0-x86" ( call "c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86 )
  - if "%C%"=="msvc-10.0-x64" ( call "c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" amd64 )
  - if "%C%"=="msvc-11.0-x86" ( call "c:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\vcvarsall.bat" x86 )
  - if "%C%"=="msvc-11.0-x64" ( call "c:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\vcvarsall.bat" amd64 )
  - if "%C%"=="msvc-12.0-x86" ( call "c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86 )
  - if "%C%"=="msvc-12.0-x64" ( call "c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64 )
  - if "%C%"=="msvc-14.0-x86" ( call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 )
  - if "%C%"=="msvc-14.0-x64" ( call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64 )

build_script:
  - set B=release
  - cd c:\projects\upx
#  - if "%C%"=="gcc-m64" ( bash -x ./.github/travis_build.sh && exit 0 ) # TODO
  - set DEFS=-D_CRT_SECURE_NO_WARNINGS
  - set BDIR=c:\projects\build\%C%\%B%
  - mkdir %BDIR% %BDIR%\ucl-1.03 %BDIR%\upx %BDIR%\upx-testsuite %BDIR%\zlib-1.2.8
  - cd %BDIR%\ucl-1.03
  - set s=c:\projects\deps\ucl-1.03
  - cl -MT -O2 -W4 %DEFS% -I%s%\include -I%s% -c %s%\src\*.c
  - link -lib -out:ucl.lib *.obj
  - cd %BDIR%\zlib-1.2.8
  - cl -MT -O2 -W2 %DEFS% -c c:\projects\deps\zlib-1.2.8\*.c
  - link -lib -out:zlib.lib *.obj
  - cd %BDIR%\upx
  - set s=c:\projects\upx\src
  - cl -MT -EHsc -O2 -W4 -wd4244 %DEFS% -DWITH_LZMA=0x443 -DUCL_NO_ASM -I%s%\lzma-sdk -Ic:\projects\deps\ucl-1.03\include -Ic:\projects\deps\zlib-1.2.8 -Feupx.exe %s%\*.cpp %BDIR%\ucl-1.03\ucl.lib %BDIR%\zlib-1.2.8\zlib.lib


test_script:
  - cd %BDIR%\upx
  - .\upx.exe --version
  - .\upx.exe upx.exe -o upx_packed.exe
  - dir *.exe
  - .\upx_packed.exe --version
  - cd c:\projects\upx
  - bash ./.github/travis_testsuite_1.sh

# vim:set ts=2 sw=2 et:
