# Support for Circle CI -- https://circleci.com/gh/upx/upx
# Copyright (C) Markus Franz Xaver Johannes Oberhumer

branches:
  only:
    - circle
    - devel

machine:
  environment:
    TRAVIS_OS_NAME: linux
    C: gcc-4.8-m64
    B: release
    ALLOW_FAIL:

checkout:
  post:
    - git submodule update --init --recursive

dependencies:
  pre:
    - mkdir -p ../deps
    - cd ../deps && wget --no-check-certificate -q -O - https://download.freenas.org/distfiles/ucl-1.03.tar.gz | tar -xz
    - cd ../deps && git clone https://github.com/upx/upx-testsuite
  override:
    - bash ./.github/travis_build.sh

test:
  override:
    - bash ./.github/travis_testsuite.sh

# vim:set ts=2 sw=2 et:
